### ISSUE TITLE
how to use YQ5 dataset?

### ISSUE THREAD

**Issue by yuanhai-zou** [syywh/YQ5#1]
The YQ5 dataset is a very good job. So I plan to use it in my project. When I wanted to download the dataset, I found that the "20180129" folder was empty. At the same time, I don't know how to manipulate the dataset under ubuntu, because the suffix of each file is very strange, such as thomas_2017-08-27-15-22-11.bag.tar.gz.01. So please complete the data set and tell me how to operate the data set. I will be very grateful.

**Comment by syywh** [comment]
Thanks for your interest. I'll upload the left data soon.
The original bag is too large to be uploaded to the Baidu Netdisk. So I compress them into several small bags. You can decompress them using the following command under the directory of the downloaded data
`cat thomas_2017-08-28-17-06-06.bag.tar.gz.* > thomas_2017-08-28-17-06-06.bag.tar.gz`

And I'll upload a launch soon which could be used to play the bag.

**Comment by syywh** [comment]
Hi, @zhhclamber. 
The dataset is complete now. Welcome to use it and please contact me if you have any problem.

**Comment by yuanhai-zou** [comment]
Thank you very much, I will use these datasets in my experiment. Currently, I am  researching on the issue of "long-term SLAM", so I have also followed some of your articles. Maybe I have some questions about datasets or articles that I want to consult with you in the future. In order to better contact you, can you leave your contact information?

**Comment by syywh** [comment]
You can email me at xqding@zju.edu.cn.
